### ISSUE TITLE
🐞 [BUG] Passport Bug

### ISSUE THREAD

**Issue by yonocan** [gitcoinco/dPopp#131] opened 2022-06-02 13:26 UTC
See thread for details: https://discord.com/channels/562828676480237578/953718165341364324/981890513860968508

Everything hanging / issues around 2022-06-02 10:00:00 AM UTC
Says it works again 2022-06-02 12:40:00 UTC

**Comment by shavinac** [comment] 2022-06-02 20:49
Debugging attempts:
- no relevant Cloudwatch logs for IAM, ipfs/ceramic containers during the affected time period
- no relevant container events during

**Comment by shavinac** [comment] 2022-06-03 13:58
Closing due to lack of info for diagnosing root cause

**Closed by shavinac** 2022-06-03 13:58 UTC
